// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupData.proto

package protocol.Data;

public final class GroupData {
  private GroupData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GroupItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.GroupItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string groupId = 1;</code>
     */
    boolean hasGroupId();
    /**
     * <code>required string groupId = 1;</code>
     */
    java.lang.String getGroupId();
    /**
     * <code>required string groupId = 1;</code>
     */
    com.google.protobuf.ByteString
        getGroupIdBytes();

    /**
     * <code>required string groupName = 2;</code>
     */
    boolean hasGroupName();
    /**
     * <code>required string groupName = 2;</code>
     */
    java.lang.String getGroupName();
    /**
     * <code>required string groupName = 2;</code>
     */
    com.google.protobuf.ByteString
        getGroupNameBytes();

    /**
     * <code>repeated string memberUserId = 3;</code>
     */
    com.google.protobuf.ProtocolStringList
        getMemberUserIdList();
    /**
     * <code>repeated string memberUserId = 3;</code>
     */
    int getMemberUserIdCount();
    /**
     * <code>repeated string memberUserId = 3;</code>
     */
    java.lang.String getMemberUserId(int index);
    /**
     * <code>repeated string memberUserId = 3;</code>
     */
    com.google.protobuf.ByteString
        getMemberUserIdBytes(int index);

    /**
     * <code>required string createrUserId = 4;</code>
     */
    boolean hasCreaterUserId();
    /**
     * <code>required string createrUserId = 4;</code>
     */
    java.lang.String getCreaterUserId();
    /**
     * <code>required string createrUserId = 4;</code>
     */
    com.google.protobuf.ByteString
        getCreaterUserIdBytes();
  }
  /**
   * Protobuf type {@code protocol.GroupItem}
   */
  public static final class GroupItem extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protocol.GroupItem)
      GroupItemOrBuilder {
    // Use GroupItem.newBuilder() to construct.
    private GroupItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GroupItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GroupItem defaultInstance;
    public static GroupItem getDefaultInstance() {
      return defaultInstance;
    }

    public GroupItem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GroupItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              groupId_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              groupName_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                memberUserId_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              memberUserId_.add(bs);
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              createrUserId_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          memberUserId_ = memberUserId_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Data.GroupData.internal_static_protocol_GroupItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Data.GroupData.internal_static_protocol_GroupItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Data.GroupData.GroupItem.class, protocol.Data.GroupData.GroupItem.Builder.class);
    }

    public static com.google.protobuf.Parser<GroupItem> PARSER =
        new com.google.protobuf.AbstractParser<GroupItem>() {
      public GroupItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GroupItem(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GroupItem> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int GROUPID_FIELD_NUMBER = 1;
    private java.lang.Object groupId_;
    /**
     * <code>required string groupId = 1;</code>
     */
    public boolean hasGroupId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string groupId = 1;</code>
     */
    public java.lang.String getGroupId() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          groupId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string groupId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUPNAME_FIELD_NUMBER = 2;
    private java.lang.Object groupName_;
    /**
     * <code>required string groupName = 2;</code>
     */
    public boolean hasGroupName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string groupName = 2;</code>
     */
    public java.lang.String getGroupName() {
      java.lang.Object ref = groupName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          groupName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string groupName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getGroupNameBytes() {
      java.lang.Object ref = groupName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MEMBERUSERID_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList memberUserId_;
    /**
     * <code>repeated string memberUserId = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getMemberUserIdList() {
      return memberUserId_;
    }
    /**
     * <code>repeated string memberUserId = 3;</code>
     */
    public int getMemberUserIdCount() {
      return memberUserId_.size();
    }
    /**
     * <code>repeated string memberUserId = 3;</code>
     */
    public java.lang.String getMemberUserId(int index) {
      return memberUserId_.get(index);
    }
    /**
     * <code>repeated string memberUserId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMemberUserIdBytes(int index) {
      return memberUserId_.getByteString(index);
    }

    public static final int CREATERUSERID_FIELD_NUMBER = 4;
    private java.lang.Object createrUserId_;
    /**
     * <code>required string createrUserId = 4;</code>
     */
    public boolean hasCreaterUserId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string createrUserId = 4;</code>
     */
    public java.lang.String getCreaterUserId() {
      java.lang.Object ref = createrUserId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          createrUserId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string createrUserId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCreaterUserIdBytes() {
      java.lang.Object ref = createrUserId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createrUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      groupId_ = "";
      groupName_ = "";
      memberUserId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      createrUserId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasGroupId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGroupName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreaterUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getGroupIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getGroupNameBytes());
      }
      for (int i = 0; i < memberUserId_.size(); i++) {
        output.writeBytes(3, memberUserId_.getByteString(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, getCreaterUserIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getGroupIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getGroupNameBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < memberUserId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(memberUserId_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getMemberUserIdList().size();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getCreaterUserIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protocol.Data.GroupData.GroupItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Data.GroupData.GroupItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Data.GroupData.GroupItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Data.GroupData.GroupItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Data.GroupData.GroupItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Data.GroupData.GroupItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol.Data.GroupData.GroupItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol.Data.GroupData.GroupItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol.Data.GroupData.GroupItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Data.GroupData.GroupItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.Data.GroupData.GroupItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.GroupItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.GroupItem)
        protocol.Data.GroupData.GroupItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Data.GroupData.internal_static_protocol_GroupItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Data.GroupData.internal_static_protocol_GroupItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Data.GroupData.GroupItem.class, protocol.Data.GroupData.GroupItem.Builder.class);
      }

      // Construct using protocol.Data.GroupData.GroupItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        groupId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        groupName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        memberUserId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        createrUserId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Data.GroupData.internal_static_protocol_GroupItem_descriptor;
      }

      public protocol.Data.GroupData.GroupItem getDefaultInstanceForType() {
        return protocol.Data.GroupData.GroupItem.getDefaultInstance();
      }

      public protocol.Data.GroupData.GroupItem build() {
        protocol.Data.GroupData.GroupItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.Data.GroupData.GroupItem buildPartial() {
        protocol.Data.GroupData.GroupItem result = new protocol.Data.GroupData.GroupItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.groupId_ = groupId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.groupName_ = groupName_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          memberUserId_ = memberUserId_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.memberUserId_ = memberUserId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.createrUserId_ = createrUserId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Data.GroupData.GroupItem) {
          return mergeFrom((protocol.Data.GroupData.GroupItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Data.GroupData.GroupItem other) {
        if (other == protocol.Data.GroupData.GroupItem.getDefaultInstance()) return this;
        if (other.hasGroupId()) {
          bitField0_ |= 0x00000001;
          groupId_ = other.groupId_;
          onChanged();
        }
        if (other.hasGroupName()) {
          bitField0_ |= 0x00000002;
          groupName_ = other.groupName_;
          onChanged();
        }
        if (!other.memberUserId_.isEmpty()) {
          if (memberUserId_.isEmpty()) {
            memberUserId_ = other.memberUserId_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureMemberUserIdIsMutable();
            memberUserId_.addAll(other.memberUserId_);
          }
          onChanged();
        }
        if (other.hasCreaterUserId()) {
          bitField0_ |= 0x00000008;
          createrUserId_ = other.createrUserId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasGroupId()) {
          
          return false;
        }
        if (!hasGroupName()) {
          
          return false;
        }
        if (!hasCreaterUserId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Data.GroupData.GroupItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Data.GroupData.GroupItem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object groupId_ = "";
      /**
       * <code>required string groupId = 1;</code>
       */
      public boolean hasGroupId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string groupId = 1;</code>
       */
      public java.lang.String getGroupId() {
        java.lang.Object ref = groupId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            groupId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string groupId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGroupIdBytes() {
        java.lang.Object ref = groupId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string groupId = 1;</code>
       */
      public Builder setGroupId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string groupId = 1;</code>
       */
      public Builder clearGroupId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        groupId_ = getDefaultInstance().getGroupId();
        onChanged();
        return this;
      }
      /**
       * <code>required string groupId = 1;</code>
       */
      public Builder setGroupIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        groupId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object groupName_ = "";
      /**
       * <code>required string groupName = 2;</code>
       */
      public boolean hasGroupName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string groupName = 2;</code>
       */
      public java.lang.String getGroupName() {
        java.lang.Object ref = groupName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            groupName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string groupName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getGroupNameBytes() {
        java.lang.Object ref = groupName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string groupName = 2;</code>
       */
      public Builder setGroupName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        groupName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string groupName = 2;</code>
       */
      public Builder clearGroupName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        groupName_ = getDefaultInstance().getGroupName();
        onChanged();
        return this;
      }
      /**
       * <code>required string groupName = 2;</code>
       */
      public Builder setGroupNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        groupName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList memberUserId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMemberUserIdIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          memberUserId_ = new com.google.protobuf.LazyStringArrayList(memberUserId_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string memberUserId = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getMemberUserIdList() {
        return memberUserId_.getUnmodifiableView();
      }
      /**
       * <code>repeated string memberUserId = 3;</code>
       */
      public int getMemberUserIdCount() {
        return memberUserId_.size();
      }
      /**
       * <code>repeated string memberUserId = 3;</code>
       */
      public java.lang.String getMemberUserId(int index) {
        return memberUserId_.get(index);
      }
      /**
       * <code>repeated string memberUserId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMemberUserIdBytes(int index) {
        return memberUserId_.getByteString(index);
      }
      /**
       * <code>repeated string memberUserId = 3;</code>
       */
      public Builder setMemberUserId(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMemberUserIdIsMutable();
        memberUserId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string memberUserId = 3;</code>
       */
      public Builder addMemberUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMemberUserIdIsMutable();
        memberUserId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string memberUserId = 3;</code>
       */
      public Builder addAllMemberUserId(
          java.lang.Iterable<java.lang.String> values) {
        ensureMemberUserIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, memberUserId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string memberUserId = 3;</code>
       */
      public Builder clearMemberUserId() {
        memberUserId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string memberUserId = 3;</code>
       */
      public Builder addMemberUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMemberUserIdIsMutable();
        memberUserId_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object createrUserId_ = "";
      /**
       * <code>required string createrUserId = 4;</code>
       */
      public boolean hasCreaterUserId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string createrUserId = 4;</code>
       */
      public java.lang.String getCreaterUserId() {
        java.lang.Object ref = createrUserId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            createrUserId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string createrUserId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCreaterUserIdBytes() {
        java.lang.Object ref = createrUserId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          createrUserId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string createrUserId = 4;</code>
       */
      public Builder setCreaterUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        createrUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string createrUserId = 4;</code>
       */
      public Builder clearCreaterUserId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        createrUserId_ = getDefaultInstance().getCreaterUserId();
        onChanged();
        return this;
      }
      /**
       * <code>required string createrUserId = 4;</code>
       */
      public Builder setCreaterUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        createrUserId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocol.GroupItem)
    }

    static {
      defaultInstance = new GroupItem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protocol.GroupItem)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_GroupItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_GroupItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017GroupData.proto\022\010protocol\"\\\n\tGroupItem" +
      "\022\017\n\007groupId\030\001 \002(\t\022\021\n\tgroupName\030\002 \002(\t\022\024\n\014" +
      "memberUserId\030\003 \003(\t\022\025\n\rcreaterUserId\030\004 \002(" +
      "\tB\017\n\rprotocol.Data"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_GroupItem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_GroupItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_GroupItem_descriptor,
        new java.lang.String[] { "GroupId", "GroupName", "MemberUserId", "CreaterUserId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
