// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReadTableMsg.proto

package protocol.Msg;

public final class ReadTableMsg {
  private ReadTableMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReadImportantTableReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.ReadImportantTableReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string userID = 1;</code>
     */
    boolean hasUserID();
    /**
     * <code>required string userID = 1;</code>
     */
    java.lang.String getUserID();
    /**
     * <code>required string userID = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIDBytes();
  }
  /**
   * Protobuf type {@code protocol.ReadImportantTableReq}
   */
  public static final class ReadImportantTableReq extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protocol.ReadImportantTableReq)
      ReadImportantTableReqOrBuilder {
    // Use ReadImportantTableReq.newBuilder() to construct.
    private ReadImportantTableReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReadImportantTableReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReadImportantTableReq defaultInstance;
    public static ReadImportantTableReq getDefaultInstance() {
      return defaultInstance;
    }

    public ReadImportantTableReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReadImportantTableReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              userID_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Msg.ReadTableMsg.internal_static_protocol_ReadImportantTableReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Msg.ReadTableMsg.internal_static_protocol_ReadImportantTableReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Msg.ReadTableMsg.ReadImportantTableReq.class, protocol.Msg.ReadTableMsg.ReadImportantTableReq.Builder.class);
    }

    public static com.google.protobuf.Parser<ReadImportantTableReq> PARSER =
        new com.google.protobuf.AbstractParser<ReadImportantTableReq>() {
      public ReadImportantTableReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReadImportantTableReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReadImportantTableReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int USERID_FIELD_NUMBER = 1;
    private java.lang.Object userID_;
    /**
     * <code>required string userID = 1;</code>
     */
    public boolean hasUserID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string userID = 1;</code>
     */
    public java.lang.String getUserID() {
      java.lang.Object ref = userID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIDBytes() {
      java.lang.Object ref = userID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      userID_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUserID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserIDBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserIDBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protocol.Msg.ReadTableMsg.ReadImportantTableReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Msg.ReadTableMsg.ReadImportantTableReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Msg.ReadTableMsg.ReadImportantTableReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Msg.ReadTableMsg.ReadImportantTableReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Msg.ReadTableMsg.ReadImportantTableReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Msg.ReadTableMsg.ReadImportantTableReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol.Msg.ReadTableMsg.ReadImportantTableReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol.Msg.ReadTableMsg.ReadImportantTableReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol.Msg.ReadTableMsg.ReadImportantTableReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Msg.ReadTableMsg.ReadImportantTableReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.Msg.ReadTableMsg.ReadImportantTableReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.ReadImportantTableReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.ReadImportantTableReq)
        protocol.Msg.ReadTableMsg.ReadImportantTableReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Msg.ReadTableMsg.internal_static_protocol_ReadImportantTableReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Msg.ReadTableMsg.internal_static_protocol_ReadImportantTableReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Msg.ReadTableMsg.ReadImportantTableReq.class, protocol.Msg.ReadTableMsg.ReadImportantTableReq.Builder.class);
      }

      // Construct using protocol.Msg.ReadTableMsg.ReadImportantTableReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userID_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Msg.ReadTableMsg.internal_static_protocol_ReadImportantTableReq_descriptor;
      }

      public protocol.Msg.ReadTableMsg.ReadImportantTableReq getDefaultInstanceForType() {
        return protocol.Msg.ReadTableMsg.ReadImportantTableReq.getDefaultInstance();
      }

      public protocol.Msg.ReadTableMsg.ReadImportantTableReq build() {
        protocol.Msg.ReadTableMsg.ReadImportantTableReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.Msg.ReadTableMsg.ReadImportantTableReq buildPartial() {
        protocol.Msg.ReadTableMsg.ReadImportantTableReq result = new protocol.Msg.ReadTableMsg.ReadImportantTableReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userID_ = userID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Msg.ReadTableMsg.ReadImportantTableReq) {
          return mergeFrom((protocol.Msg.ReadTableMsg.ReadImportantTableReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Msg.ReadTableMsg.ReadImportantTableReq other) {
        if (other == protocol.Msg.ReadTableMsg.ReadImportantTableReq.getDefaultInstance()) return this;
        if (other.hasUserID()) {
          bitField0_ |= 0x00000001;
          userID_ = other.userID_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserID()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Msg.ReadTableMsg.ReadImportantTableReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Msg.ReadTableMsg.ReadImportantTableReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object userID_ = "";
      /**
       * <code>required string userID = 1;</code>
       */
      public boolean hasUserID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string userID = 1;</code>
       */
      public java.lang.String getUserID() {
        java.lang.Object ref = userID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userID_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIDBytes() {
        java.lang.Object ref = userID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userID = 1;</code>
       */
      public Builder setUserID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userID = 1;</code>
       */
      public Builder clearUserID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userID_ = getDefaultInstance().getUserID();
        onChanged();
        return this;
      }
      /**
       * <code>required string userID = 1;</code>
       */
      public Builder setUserIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userID_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocol.ReadImportantTableReq)
    }

    static {
      defaultInstance = new ReadImportantTableReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protocol.ReadImportantTableReq)
  }

  public interface ReadImportantTableRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.ReadImportantTableRsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .protocol.ReadImportantTableRsp.ResultCode resultCode = 1;</code>
     */
    boolean hasResultCode();
    /**
     * <code>required .protocol.ReadImportantTableRsp.ResultCode resultCode = 1;</code>
     */
    protocol.Msg.ReadTableMsg.ReadImportantTableRsp.ResultCode getResultCode();

    /**
     * <code>repeated .protocol.FriendItem friend = 2;</code>
     */
    java.util.List<protocol.Data.Friend.FriendItem> 
        getFriendList();
    /**
     * <code>repeated .protocol.FriendItem friend = 2;</code>
     */
    protocol.Data.Friend.FriendItem getFriend(int index);
    /**
     * <code>repeated .protocol.FriendItem friend = 2;</code>
     */
    int getFriendCount();
    /**
     * <code>repeated .protocol.FriendItem friend = 2;</code>
     */
    java.util.List<? extends protocol.Data.Friend.FriendItemOrBuilder> 
        getFriendOrBuilderList();
    /**
     * <code>repeated .protocol.FriendItem friend = 2;</code>
     */
    protocol.Data.Friend.FriendItemOrBuilder getFriendOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protocol.ReadImportantTableRsp}
   */
  public static final class ReadImportantTableRsp extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protocol.ReadImportantTableRsp)
      ReadImportantTableRspOrBuilder {
    // Use ReadImportantTableRsp.newBuilder() to construct.
    private ReadImportantTableRsp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReadImportantTableRsp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReadImportantTableRsp defaultInstance;
    public static ReadImportantTableRsp getDefaultInstance() {
      return defaultInstance;
    }

    public ReadImportantTableRsp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReadImportantTableRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              protocol.Msg.ReadTableMsg.ReadImportantTableRsp.ResultCode value = protocol.Msg.ReadTableMsg.ReadImportantTableRsp.ResultCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                resultCode_ = value;
              }
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                friend_ = new java.util.ArrayList<protocol.Data.Friend.FriendItem>();
                mutable_bitField0_ |= 0x00000002;
              }
              friend_.add(input.readMessage(protocol.Data.Friend.FriendItem.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          friend_ = java.util.Collections.unmodifiableList(friend_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Msg.ReadTableMsg.internal_static_protocol_ReadImportantTableRsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Msg.ReadTableMsg.internal_static_protocol_ReadImportantTableRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Msg.ReadTableMsg.ReadImportantTableRsp.class, protocol.Msg.ReadTableMsg.ReadImportantTableRsp.Builder.class);
    }

    public static com.google.protobuf.Parser<ReadImportantTableRsp> PARSER =
        new com.google.protobuf.AbstractParser<ReadImportantTableRsp>() {
      public ReadImportantTableRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReadImportantTableRsp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReadImportantTableRsp> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code protocol.ReadImportantTableRsp.ResultCode}
     */
    public enum ResultCode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SUCCESS = 0;</code>
       */
      SUCCESS(0, 0),
      /**
       * <code>FAIL = 1;</code>
       */
      FAIL(1, 1),
      ;

      /**
       * <code>SUCCESS = 0;</code>
       */
      public static final int SUCCESS_VALUE = 0;
      /**
       * <code>FAIL = 1;</code>
       */
      public static final int FAIL_VALUE = 1;


      public final int getNumber() { return value; }

      public static ResultCode valueOf(int value) {
        switch (value) {
          case 0: return SUCCESS;
          case 1: return FAIL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ResultCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ResultCode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ResultCode>() {
              public ResultCode findValueByNumber(int number) {
                return ResultCode.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protocol.Msg.ReadTableMsg.ReadImportantTableRsp.getDescriptor().getEnumTypes().get(0);
      }

      private static final ResultCode[] VALUES = values();

      public static ResultCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ResultCode(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protocol.ReadImportantTableRsp.ResultCode)
    }

    private int bitField0_;
    public static final int RESULTCODE_FIELD_NUMBER = 1;
    private protocol.Msg.ReadTableMsg.ReadImportantTableRsp.ResultCode resultCode_;
    /**
     * <code>required .protocol.ReadImportantTableRsp.ResultCode resultCode = 1;</code>
     */
    public boolean hasResultCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .protocol.ReadImportantTableRsp.ResultCode resultCode = 1;</code>
     */
    public protocol.Msg.ReadTableMsg.ReadImportantTableRsp.ResultCode getResultCode() {
      return resultCode_;
    }

    public static final int FRIEND_FIELD_NUMBER = 2;
    private java.util.List<protocol.Data.Friend.FriendItem> friend_;
    /**
     * <code>repeated .protocol.FriendItem friend = 2;</code>
     */
    public java.util.List<protocol.Data.Friend.FriendItem> getFriendList() {
      return friend_;
    }
    /**
     * <code>repeated .protocol.FriendItem friend = 2;</code>
     */
    public java.util.List<? extends protocol.Data.Friend.FriendItemOrBuilder> 
        getFriendOrBuilderList() {
      return friend_;
    }
    /**
     * <code>repeated .protocol.FriendItem friend = 2;</code>
     */
    public int getFriendCount() {
      return friend_.size();
    }
    /**
     * <code>repeated .protocol.FriendItem friend = 2;</code>
     */
    public protocol.Data.Friend.FriendItem getFriend(int index) {
      return friend_.get(index);
    }
    /**
     * <code>repeated .protocol.FriendItem friend = 2;</code>
     */
    public protocol.Data.Friend.FriendItemOrBuilder getFriendOrBuilder(
        int index) {
      return friend_.get(index);
    }

    private void initFields() {
      resultCode_ = protocol.Msg.ReadTableMsg.ReadImportantTableRsp.ResultCode.SUCCESS;
      friend_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResultCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getFriendCount(); i++) {
        if (!getFriend(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, resultCode_.getNumber());
      }
      for (int i = 0; i < friend_.size(); i++) {
        output.writeMessage(2, friend_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, resultCode_.getNumber());
      }
      for (int i = 0; i < friend_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, friend_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protocol.Msg.ReadTableMsg.ReadImportantTableRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Msg.ReadTableMsg.ReadImportantTableRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Msg.ReadTableMsg.ReadImportantTableRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Msg.ReadTableMsg.ReadImportantTableRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Msg.ReadTableMsg.ReadImportantTableRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Msg.ReadTableMsg.ReadImportantTableRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol.Msg.ReadTableMsg.ReadImportantTableRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol.Msg.ReadTableMsg.ReadImportantTableRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol.Msg.ReadTableMsg.ReadImportantTableRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Msg.ReadTableMsg.ReadImportantTableRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.Msg.ReadTableMsg.ReadImportantTableRsp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.ReadImportantTableRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.ReadImportantTableRsp)
        protocol.Msg.ReadTableMsg.ReadImportantTableRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Msg.ReadTableMsg.internal_static_protocol_ReadImportantTableRsp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Msg.ReadTableMsg.internal_static_protocol_ReadImportantTableRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Msg.ReadTableMsg.ReadImportantTableRsp.class, protocol.Msg.ReadTableMsg.ReadImportantTableRsp.Builder.class);
      }

      // Construct using protocol.Msg.ReadTableMsg.ReadImportantTableRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFriendFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        resultCode_ = protocol.Msg.ReadTableMsg.ReadImportantTableRsp.ResultCode.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (friendBuilder_ == null) {
          friend_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          friendBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Msg.ReadTableMsg.internal_static_protocol_ReadImportantTableRsp_descriptor;
      }

      public protocol.Msg.ReadTableMsg.ReadImportantTableRsp getDefaultInstanceForType() {
        return protocol.Msg.ReadTableMsg.ReadImportantTableRsp.getDefaultInstance();
      }

      public protocol.Msg.ReadTableMsg.ReadImportantTableRsp build() {
        protocol.Msg.ReadTableMsg.ReadImportantTableRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.Msg.ReadTableMsg.ReadImportantTableRsp buildPartial() {
        protocol.Msg.ReadTableMsg.ReadImportantTableRsp result = new protocol.Msg.ReadTableMsg.ReadImportantTableRsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resultCode_ = resultCode_;
        if (friendBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            friend_ = java.util.Collections.unmodifiableList(friend_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.friend_ = friend_;
        } else {
          result.friend_ = friendBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Msg.ReadTableMsg.ReadImportantTableRsp) {
          return mergeFrom((protocol.Msg.ReadTableMsg.ReadImportantTableRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Msg.ReadTableMsg.ReadImportantTableRsp other) {
        if (other == protocol.Msg.ReadTableMsg.ReadImportantTableRsp.getDefaultInstance()) return this;
        if (other.hasResultCode()) {
          setResultCode(other.getResultCode());
        }
        if (friendBuilder_ == null) {
          if (!other.friend_.isEmpty()) {
            if (friend_.isEmpty()) {
              friend_ = other.friend_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureFriendIsMutable();
              friend_.addAll(other.friend_);
            }
            onChanged();
          }
        } else {
          if (!other.friend_.isEmpty()) {
            if (friendBuilder_.isEmpty()) {
              friendBuilder_.dispose();
              friendBuilder_ = null;
              friend_ = other.friend_;
              bitField0_ = (bitField0_ & ~0x00000002);
              friendBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFriendFieldBuilder() : null;
            } else {
              friendBuilder_.addAllMessages(other.friend_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResultCode()) {
          
          return false;
        }
        for (int i = 0; i < getFriendCount(); i++) {
          if (!getFriend(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Msg.ReadTableMsg.ReadImportantTableRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Msg.ReadTableMsg.ReadImportantTableRsp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private protocol.Msg.ReadTableMsg.ReadImportantTableRsp.ResultCode resultCode_ = protocol.Msg.ReadTableMsg.ReadImportantTableRsp.ResultCode.SUCCESS;
      /**
       * <code>required .protocol.ReadImportantTableRsp.ResultCode resultCode = 1;</code>
       */
      public boolean hasResultCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .protocol.ReadImportantTableRsp.ResultCode resultCode = 1;</code>
       */
      public protocol.Msg.ReadTableMsg.ReadImportantTableRsp.ResultCode getResultCode() {
        return resultCode_;
      }
      /**
       * <code>required .protocol.ReadImportantTableRsp.ResultCode resultCode = 1;</code>
       */
      public Builder setResultCode(protocol.Msg.ReadTableMsg.ReadImportantTableRsp.ResultCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        resultCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .protocol.ReadImportantTableRsp.ResultCode resultCode = 1;</code>
       */
      public Builder clearResultCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resultCode_ = protocol.Msg.ReadTableMsg.ReadImportantTableRsp.ResultCode.SUCCESS;
        onChanged();
        return this;
      }

      private java.util.List<protocol.Data.Friend.FriendItem> friend_ =
        java.util.Collections.emptyList();
      private void ensureFriendIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          friend_ = new java.util.ArrayList<protocol.Data.Friend.FriendItem>(friend_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          protocol.Data.Friend.FriendItem, protocol.Data.Friend.FriendItem.Builder, protocol.Data.Friend.FriendItemOrBuilder> friendBuilder_;

      /**
       * <code>repeated .protocol.FriendItem friend = 2;</code>
       */
      public java.util.List<protocol.Data.Friend.FriendItem> getFriendList() {
        if (friendBuilder_ == null) {
          return java.util.Collections.unmodifiableList(friend_);
        } else {
          return friendBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protocol.FriendItem friend = 2;</code>
       */
      public int getFriendCount() {
        if (friendBuilder_ == null) {
          return friend_.size();
        } else {
          return friendBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protocol.FriendItem friend = 2;</code>
       */
      public protocol.Data.Friend.FriendItem getFriend(int index) {
        if (friendBuilder_ == null) {
          return friend_.get(index);
        } else {
          return friendBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protocol.FriendItem friend = 2;</code>
       */
      public Builder setFriend(
          int index, protocol.Data.Friend.FriendItem value) {
        if (friendBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFriendIsMutable();
          friend_.set(index, value);
          onChanged();
        } else {
          friendBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.FriendItem friend = 2;</code>
       */
      public Builder setFriend(
          int index, protocol.Data.Friend.FriendItem.Builder builderForValue) {
        if (friendBuilder_ == null) {
          ensureFriendIsMutable();
          friend_.set(index, builderForValue.build());
          onChanged();
        } else {
          friendBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.FriendItem friend = 2;</code>
       */
      public Builder addFriend(protocol.Data.Friend.FriendItem value) {
        if (friendBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFriendIsMutable();
          friend_.add(value);
          onChanged();
        } else {
          friendBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.FriendItem friend = 2;</code>
       */
      public Builder addFriend(
          int index, protocol.Data.Friend.FriendItem value) {
        if (friendBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFriendIsMutable();
          friend_.add(index, value);
          onChanged();
        } else {
          friendBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.FriendItem friend = 2;</code>
       */
      public Builder addFriend(
          protocol.Data.Friend.FriendItem.Builder builderForValue) {
        if (friendBuilder_ == null) {
          ensureFriendIsMutable();
          friend_.add(builderForValue.build());
          onChanged();
        } else {
          friendBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.FriendItem friend = 2;</code>
       */
      public Builder addFriend(
          int index, protocol.Data.Friend.FriendItem.Builder builderForValue) {
        if (friendBuilder_ == null) {
          ensureFriendIsMutable();
          friend_.add(index, builderForValue.build());
          onChanged();
        } else {
          friendBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.FriendItem friend = 2;</code>
       */
      public Builder addAllFriend(
          java.lang.Iterable<? extends protocol.Data.Friend.FriendItem> values) {
        if (friendBuilder_ == null) {
          ensureFriendIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, friend_);
          onChanged();
        } else {
          friendBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.FriendItem friend = 2;</code>
       */
      public Builder clearFriend() {
        if (friendBuilder_ == null) {
          friend_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          friendBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protocol.FriendItem friend = 2;</code>
       */
      public Builder removeFriend(int index) {
        if (friendBuilder_ == null) {
          ensureFriendIsMutable();
          friend_.remove(index);
          onChanged();
        } else {
          friendBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.FriendItem friend = 2;</code>
       */
      public protocol.Data.Friend.FriendItem.Builder getFriendBuilder(
          int index) {
        return getFriendFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protocol.FriendItem friend = 2;</code>
       */
      public protocol.Data.Friend.FriendItemOrBuilder getFriendOrBuilder(
          int index) {
        if (friendBuilder_ == null) {
          return friend_.get(index);  } else {
          return friendBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protocol.FriendItem friend = 2;</code>
       */
      public java.util.List<? extends protocol.Data.Friend.FriendItemOrBuilder> 
           getFriendOrBuilderList() {
        if (friendBuilder_ != null) {
          return friendBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(friend_);
        }
      }
      /**
       * <code>repeated .protocol.FriendItem friend = 2;</code>
       */
      public protocol.Data.Friend.FriendItem.Builder addFriendBuilder() {
        return getFriendFieldBuilder().addBuilder(
            protocol.Data.Friend.FriendItem.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol.FriendItem friend = 2;</code>
       */
      public protocol.Data.Friend.FriendItem.Builder addFriendBuilder(
          int index) {
        return getFriendFieldBuilder().addBuilder(
            index, protocol.Data.Friend.FriendItem.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol.FriendItem friend = 2;</code>
       */
      public java.util.List<protocol.Data.Friend.FriendItem.Builder> 
           getFriendBuilderList() {
        return getFriendFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protocol.Data.Friend.FriendItem, protocol.Data.Friend.FriendItem.Builder, protocol.Data.Friend.FriendItemOrBuilder> 
          getFriendFieldBuilder() {
        if (friendBuilder_ == null) {
          friendBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protocol.Data.Friend.FriendItem, protocol.Data.Friend.FriendItem.Builder, protocol.Data.Friend.FriendItemOrBuilder>(
                  friend_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          friend_ = null;
        }
        return friendBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protocol.ReadImportantTableRsp)
    }

    static {
      defaultInstance = new ReadImportantTableRsp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protocol.ReadImportantTableRsp)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_ReadImportantTableReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_ReadImportantTableReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_ReadImportantTableRsp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_ReadImportantTableRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ReadTableMsg.proto\022\010protocol\032\014Friend.p" +
      "roto\"\'\n\025ReadImportantTableReq\022\016\n\006userID\030" +
      "\001 \002(\t\"\242\001\n\025ReadImportantTableRsp\022>\n\nresul" +
      "tCode\030\001 \002(\0162*.protocol.ReadImportantTabl" +
      "eRsp.ResultCode\022$\n\006friend\030\002 \003(\0132\024.protoc" +
      "ol.FriendItem\"#\n\nResultCode\022\013\n\007SUCCESS\020\000" +
      "\022\010\n\004FAIL\020\001B\016\n\014protocol.Msg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protocol.Data.Friend.getDescriptor(),
        }, assigner);
    internal_static_protocol_ReadImportantTableReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_ReadImportantTableReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_ReadImportantTableReq_descriptor,
        new java.lang.String[] { "UserID", });
    internal_static_protocol_ReadImportantTableRsp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_ReadImportantTableRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_ReadImportantTableRsp_descriptor,
        new java.lang.String[] { "ResultCode", "Friend", });
    protocol.Data.Friend.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
